version: 0.2

phases:
  install:    
    commands:
      - echo "Installing PostgreSQL client..."
      - amazon-linux-extras enable postgresql14
      - yum install -y postgresql
  build:
    commands:
      - echo "Setting up database and user..."
      - psql "host=$DB_HOST port=5432 user=$DB_ADMIN_USER password=$DB_ADMIN_PASSWORD dbname=postgres" -f rds_setup.sql
      - psql "host=$DB_HOST port=5432 user=$DB_ADMIN_USER password=$DB_ADMIN_PASSWORD dbname=mydb" -f rds_setup2.sql