GRANT ALL ON SCHEMA public TO nazar;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nazar;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO nazar;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO nazar;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO nazar;